package Domains.Amazon;

public class WebElements {
    public static final String topSearchBar = "//input[@id='twotabsearchtextbox']";
    public static final String topSearchButton = "//input[@id='nav-search-submit-button']";
    public static final String signInAnchor = "//a[@id='nav-link-accountList']";
    public static final String emailField = "//input[@type='email']";
    public static final String signInContinue = "//input[@id='continue']";
    public static final String createAccSubmit = "//a[@id='createAccountSubmit']";
    public static final String customerNameinput = "//input[@id='ap_customer_name']";
    public static final String customerEmailinput = "//input[@id='ap_email']";
    public static final String customerPasswordInput = "//input[@id='ap_password']";
    public static final String customerPasswordCheckInput = "//input[@id='ap_password_check']";
    public static final String createAccountSubmit = "//input[@id='continue']";
    public static final String selectHoodie = "//span[contains(text(), 'Pullover Club Hoodie')]";
    public static final String sizeChoice = "//input[@aria-labelledby=\"size_name_1-announce\"]";
    public static final String addToCartButton = "//input[@id='add-to-cart-button']";
    public static final String sizeDropDown = "//span[@class=\"a-dropdown-prompt\"]";
    public static final String selectSizeFromDropper = "//li[@id=\"size_name_1\"]";
    public static final String navToCart = "//a[@id=\"nav-cart\"]";
    public static final String qtyDropdown = "//span[@id=\"a-autoid-0-announce\"]";
    public static final String qtyDropdownSelection = "//ul/li[7]/a[@id=\"quantity_6\"]";
    public static final String accManager = "//span[@id=\"nav-link-accountList-nav-line-1\"]";
    public static final String signOut = "//a[@id=\"nav-item-signout\"]";
    public static final String loginSecurity = "//div[@data-card-identifier=\"SignInAndSecurity_C\"]";
    public static final String hubPassword = "//span[@id=\"PASSWORD_BUTTON\"]";
    public static final String passwordchangeOld = "//input[@id=\"ap_password\"]";
    public static final String passwordChangeNew = "//input[@id=\"ap_password_new\"]";
    public static final String passwordChangeCheck = "//input[@id=\"ap_password_new_check\"]";
    public static final String rememberMe = "//input[@name=\"rememberMe\"]";
    public static final String passwordChangeSubmit = "//input[@id=\"cnep_1D_submit_button\"]";
    public static final String hubAddresses = "//div[@data-card-identifier=\"AddressesAnd1Click\"]";
    public static final String addAddress = "//div[@id=\"ya-myab-plus-address-icon\"]";
    public static final String addressName = "//input[@id=\"address-ui-widgets-enterAddressLine1\"]";
    public static final String addressCity = "//input[@id=\"address-ui-widgets-enterAddressCity\"]";
    public static final String addressStateDropdown = "//span[@id=\"select2-address-ui-widgets-enterAddressStateOrRegion-dropdown-nativeId-container\"]";
    public static final String addressDropdownClick = "//input[@class=\"select2-search__field\"]";
    public static final String addressZip = "//input[@id=\"address-ui-widgets-enterAddressPostalCode\"]";
    public static final String addressSubmit = "//span[@id=\"address-ui-widgets-form-submit-button-announce\"]";
    public static final String addressType = "//button[@aria-label=\"House\"]";
    public static final String addressPrefer = "//input[@type='radio' and @name='preferredDeliveryLocationHOUSE' and @value='REAR_DOOR']";
    public static final String addressAdd = "//span[@id=\"address-ui-widgets-form-submit-button\"]";
    public static final String addressSave = "//input[@name=\"address-ui-widgets-saveOriginalOrSuggestedAddress\"]";

    public static final String accHubPracticeXpath = "//*[@id=\"nav-link-accountList-nav-line-1\"]";
    public static final String yourProfileXpath = "//*[@id=\"a-page\"]/div[1]/div/div[4]/div[1]/a/div/div/div/div[2]/h2";
    public static final String defaultProfileXpath = "//p[@id=\"home-profile-active\"]";
    public static final String clickEditXpath = "//*[@id=\"mobile-number-edit-link\"]/img";
    public static final String numberInputXpath = "//*[@id=\"cvf-page-content\"]/div/div/div/form/div[1]/div/div[2]/div/div[2]/input";
}